name = "am-store-luxury-watches"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
main = "src/index.ts"
compatibility_date = "2024-01-18"

[env.production]
name = "am-store-luxury-watches-prod"
